version: '3.7'

services:
  prometheus:
    image: prom/prometheus
    container_name: soa-library-prometheus
    volumes:
      # *** Đã cập nhật đường dẫn tuyệt đối cho file cấu hình ***
      - "D:/CODING/code/python/soa/INT3505E_01_demo/lab10_api_monitoring/prometheus.yml:/etc/prometheus/prometheus.yml"
      # Volume để lưu trữ dữ liệu (giữ nguyên)
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      # - --web.console.libraries=/usr/share/prometheus/console_libraries
      # - --web.console.html=/usr/share/prometheus/console
    ports:
      - "9090:9090"
    restart: unless-stopped

# Định nghĩa Volume để lưu trữ dữ liệu lâu dài
volumes:
  prometheus_data: